"""02 — Backend swap demo (optional dependencies).

Goal: show that the *same task* can be run with different backends.

We do two runs:
1) Native backend (always available)
2) DeepXDE backend (only if `deepxde` is installed)

Because DeepXDEBackend needs `bundle.sensors`, this script *creates* a temporary
bundle by distilling pseudo-sensors from a quickly trained native model.

Run from repo root:
    python examples/arena/02_backend_swap_optional.py
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from pinneaple_arena.bundle.loader import load_bundle
from pinneaple_arena.bundle.schema import load_bundle_schema
from pinneaple_arena.runner.run_benchmark import run_benchmark
from pinneaple_arena.registry import list_backends


def _make_tmp_bundle_with_sensors(repo_root: Path, *, out_root: Path) -> Path:
    """Copy the built-in bundle and add sensors.parquet generated by a native model."""
    src = repo_root / "data" / "bundles" / "flow_obstacle_2d" / "v0"
    dst = out_root / "flow_obstacle_2d_v0_with_sensors"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)

    schema = load_bundle_schema(repo_root / "configs" / "data" / "bundle_schema.yaml")
    bundle = load_bundle(dst, schema=schema, require_sensors=False)

    # Train a tiny native model (teacher)
    from pinneaple_arena.backends.native_pinn import NativePINNBackend

    teacher_cfg = {
        "backend": {"name": "pinneaple_native"},
        "train": {"device": "cpu", "epochs": 400, "lr": 1e-3, "seed": 0, "log_every": 200, "weights": {"pde": 1.0, "bc": 10.0}},
        "arena": {"n_collocation": 1024, "n_boundary": 512},
        "model": {"hidden": [64, 64, 64], "activation": "tanh"},
    }
    teacher = NativePINNBackend().train(bundle, teacher_cfg)["model"]
    teacher.eval()

    # Create pseudo-sensors by sampling collocation points and querying the teacher
    pts = bundle.points_collocation.sample(n=min(12000, len(bundle.points_collocation)), replace=False, random_state=0)
    xy = pts[["x", "y"]].to_numpy(dtype=np.float32)

    with torch.inference_mode():
        y = teacher(torch.tensor(xy, dtype=torch.float32)).cpu().numpy()

    df = pd.DataFrame({
        "x": xy[:, 0],
        "y": xy[:, 1],
        "u": y[:, 0],
        "v": y[:, 1],
        "p": y[:, 2],
        "scenario_id": 0,
        "split": "train",
    })

    # Hold out a small test set
    n_test = max(1, len(df) // 10)
    df.loc[df.sample(n=n_test, random_state=1).index, "split"] = "test"

    sensors_path = dst / "bundle" / "sensors.parquet"
    sensors_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(sensors_path, index=False)
    return dst


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    artifacts_dir = repo_root / "artifacts" / "examples" / "backend_swap"

    print("Available backends:", list_backends())

    # 1) Native run (no sensors needed)
    out_native = run_benchmark(
        artifacts_dir=artifacts_dir,
        task_cfg_path=repo_root / "examples" / "arena" / "configs" / "task_flow_obstacle_2d.yaml",
        run_cfg_path=repo_root / "examples" / "arena" / "configs" / "run_native_fast.yaml",
        bundle_schema_path=repo_root / "configs" / "data" / "bundle_schema.yaml",
    )
    print("\n[1/2] Native summary:", out_native["summary"]["key_metrics"])

    # 2) DeepXDE run (optional)
    try:
        import deepxde  # noqa: F401
    except Exception:
        print("\n[2/2] Skipping DeepXDE run: deepxde is not installed. Try: pip install deepxde")
        return

    tmp_bundle = _make_tmp_bundle_with_sensors(repo_root, out_root=artifacts_dir)

    # Build a task config on the fly pointing at the temp bundle
    tmp_task_cfg = artifacts_dir / "tmp_task_deepxde.yaml"
    tmp_task_cfg.write_text(
        "\n".join(
            [
                "task_id: flow_obstacle_2d",
                f"bundle_root: {tmp_bundle.as_posix()}",
                "require_sensors: true",
                "",
            ]
        ),
        encoding="utf-8",
    )

    deepxde_run_cfg = artifacts_dir / "tmp_run_deepxde.yaml"
    deepxde_run_cfg.write_text(
        "\n".join(
            [
                "run_name: deepxde_demo",
                "",
                "backend:",
                "  name: deepxde",
                "",
                "train:",
                "  epochs: 2000",
                "  lr: 0.001",
                "  deepxde_backend: tensorflow",  # works for most users
                "",
                "model:",
                "  width: 128",
                "  depth: 3",
                "  activation: tanh",
                "",
            ]
        ),
        encoding="utf-8",
    )

    out_dx = run_benchmark(
        artifacts_dir=artifacts_dir,
        task_cfg_path=tmp_task_cfg,
        run_cfg_path=deepxde_run_cfg,
        bundle_schema_path=repo_root / "configs" / "data" / "bundle_schema.yaml",
    )
    print("\n[2/2] DeepXDE summary:", out_dx["summary"]["key_metrics"])

    print("\nLeaderboard:", artifacts_dir / "leaderboard.json")


if __name__ == "__main__":
    main()
