apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinneapple-registry-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.registry.storageSize }}
